insert into contact (first_name, last_name, birth_date, description) values ('Zep', 'Brennigan', '1988-09-09', 'Default description');
insert into contact (first_name, last_name, birth_date, description) values ('Bender', 'Rodriges', '1988-08-09', 'Default description');
insert into contact (first_name, last_name, birth_date, description) values ('Rakkaus', 'Prophet', '1988-09-09', 'Default description');
insert into contact (first_name, last_name, birth_date, description) values ('Lila', 'Singleye', '1988-04-06', 'Default description');
insert into contact (first_name, last_name, birth_date, description) values ('Doctor', 'Zoildberg', '1988-05-09', 'Default description');
insert into contact (first_name, last_name, birth_date, description) values ('Pudge', 'Chinchope', '1988-01-09', 'Default description');
insert into contact (first_name, last_name, birth_date, description) values ('Hulk', 'Incredible', '1988-02-09', 'Default description');
insert into contact (first_name, last_name, birth_date, description) values ('Capitan', 'America', '1988-04-09', 'Default description');
insert into contact (first_name, last_name, birth_date, description) values ('Willy', 'Wonka', '1988-03-09', 'Default description');